export const ADDED_FLOWER = "ADDED_FLOWER";
export const UPDATED_FLOWER = "UPDATED_FLOWER";
export const LOADED_FORM = "LOADED_FORM";
export const CHECK_LOGIN_STATUS = "CHECK_LOGIN_STATUS";
export const DELETED_FLOWER = "DELETED_FLOWER";
export const LOADED_FLOWERS = "LOADED_FLOWERS";

